
    inline const char PUSH_CODE = 0;
    inline const char POP_CODE = 1;
    inline const char ADD_CODE = 16;
    inline const char SUB_CODE = 17;
    inline const char DIV_CODE = 18;
    inline const char MOD_CODE = 19;
    inline const char SQRT_CODE = 20;
    inline const char GOTO_CODE = 32;
    inline const char IN_CODE = 48;
    inline const char OUT_CODE = 49;
    inline const char END_CODE = 64;